### ISSUE TITLE
500 server error -- server:Kestrel

### ISSUE THREAD

**Issue by jaumemiralles** [cmu-sei/GHOSTS-ANIMATOR#6] opened 2022-11-21 08:28 UTC
Hi, I'll try your animator, I've done the steps of the quick start guide, I can connect to http://localhost:6001/swagger but when I try to do anything I get a 500 server error -- server:Kestrel

#docker ps
I've the mongodb container in STATUS "Restarting"... the other one is UP.

Can you help me?

_Originally posted by @jaumemiralles in https://github.com/cmu-sei/GHOSTS-ANIMATOR/issues/2#issuecomment-1321138887_

**Comment by sei-dupdyke** [comment] 2022-11-22 13:37
I'm closing this issue as it seems a duplicate of #2

**Closed by sei-dupdyke** 2022-11-22 13:37 UTC
